#自定义的一些资源
resources:
  itext7-font:
    - D:\workspace\IdeaProjects\bat\laoyin\font\NotoSansCJKsc-Regular.otf
    - D:\workspace\IdeaProjects\production-system\laoyin\font\NotoSansCJKsc-Regular.otf
  pdfbox-font:
    - D:\workspace\IdeaProjects\production-system\laoyin\font\SourceHanSansCN-Regular.ttf
  file-path: ${java.io.tmpdir}
spring:
  datasource:
    name: laoyin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.limlim.cn:3306/laoyin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: bat
  resources:
    static-locations: [ "/META-INF/resources/", "/resources/", "/static/", "/public/", "file:${resources.web-extend-dir}" ]
print:
  url: http://bat.com/
logistics:
  kdn:
    EBusinessID: ""
    ApiKey: ""
    ReqURL : "http://sandboxapi.kdniao.com:8080/kdniaosandbox/gateway/exterfaceInvoke.json"
  zto:
    CustomerName: testzto
    CustomerPwd: testztopwd
  jtsd:
    CustomerName:
    CustomerPwd:
#https://github.com/alibaba/jetcache/blob/master/samples/springbootsample/src/main/resources/application.yml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6380
      password: bat
      masterName: laoyin-service
#https://www.xuxueli.com/xxl-job/
### 定时任务配置
xxl:
  job:
    admin:
      ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册
      addresses: http://192.168.0.220:9092/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: 7A7277ADCD89A5A71C25583A55BBA69C
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: job-executor-laoyin
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题
      address:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口
      port: 9999
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径
      logPath: /data/applogs/xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能
      logretentiondays: 100
    ### 调度类型
    scheduleType: CRON
    ### 运行模式
    glueType: BEAN
    ### 路由策略
    executorRouteStrategy: FIRST
    ### 调度过期策略
    misfireStrategy: DO_NOTHING
    ### 阻塞处理策略
    executorBlockStrategy: SERIAL_EXECUTION
    ### 任务超时时间
    executorTimeout: 0
    ### 失败重试次数
    executorFailRetryCount: 3
    ### 调度中心登录用户名
    userName: admin
    ### 调度中心登录密码
    password: bat
    ifRemember: on

    ### 定时任务调度中心地址
    baseUri: http://192.168.0.220:9092/xxl-job-admin
    ### 定时任务新建地址
    JOB_INFO_ADD_URI: /jobinfo/add
    ### 定时任务查询地址
    JOB_INFO_LIST_URI: /jobinfo/pageList
    ### 定时任务查询地址
    JOB_INFO_LOGIN_URI: /login
    ### 定时任务启动地址
    JOB_INFO_START_URI: /jobinfo/start
    ### 定时任务修改请求地址
    JOB_INFO_UPDATE_URI: /jobinfo/update
    ### 定时任务删除请求地址
    JOB_INFO_DELETE_URI: /jobinfo/remove
    ### 执行器
    actuator:
      laoyin:
        ## 柔性的执行器ID
        id: 1