spring:
  application:
    name: laoyin-service
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/doc/temp/
    mode: HTML5

server:
  port: 8078
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.bat.laoyin.dao.*.dataobject
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      update-strategy: ignored
      logic-delete-field: delete_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)